### ISSUE TITLE
[Feature Request] Support for 5 ?

### ISSUE THREAD

**Issue by niladam** [Laravel-Backpack/medialibrary-uploaders#21]
# Support this in v5 version?

I was thinking i could use this on a v5 project. I'm curious as to why this is >= 6.* only ?

What is the reason for that ? Is there any way i could help ?

**Comment by phpfour** [comment]
I can see from the history that it supported v5 initially, but later it was removed. 

@pxpm maybe you can share your views?

**Comment by pxpm** [comment]
Hey @niladam and @phpfour 

The reason we removed v5 support was because the Uploaders are a v6 feature.

Also we had other minor reasons to support only v6. More meaningful the PHP 7.3 support in Laravel 8. 

So to avoid it working only in some v5 installations and not on all of them, we decided to add support only to v6, that allowed us to write code that does not work on PHP 7.3. 

So yeah, all sum up, those were the reasons. Fair ? Or do you think we can address this in other way @niladam ? @phpfour ?

Cheers

**Comment by niladam** [comment]
Well, i'm currently sporting a v5 using PHP 8.2 without any issues. So, i don't understand why this hasn't also been backported to v5. Honestly, i'm a little disappointed in this :(

I can understand the need to push to v6 for the feature set looks great but for me, i'm kind of stuck on v5.

Anyways, thank you for explaining this to me.

**Comment by pxpm** [comment]
> Well, i'm currently sporting a v5 using PHP 8.2 without any issues. So, i don't understand why this hasn't also been backported to v5. Honestly, i'm a little disappointed in this :(
> 
> I can understand the need to push to v6 for the feature set looks great but for me, i'm kind of stuck on v5.
> 
> Anyways, thank you for explaining this to me.

Totally. This is compatible with php 8.2. but backpack v5 support up to Laravel 8, that support php 7.3.
For us to say that: "we support v5". It would need to support all v5 combinations. Otherwise would only "partially" support v5. 

I am open to add that "partial" support, so that we allow v5, but only if you are running v5 on Laravel 9+. 

@tabacitu what are your thoughts on this? Can/should we support v5 installations on newer PHP versions?

**Comment by niladam** [comment]
Here's my output of `php artisan backpack:version` :)


<img width="619" alt="Screenshot 2023-11-07 at 12 18 17" src="https://github.com/Laravel-Backpack/medialibrary-uploaders/assets/4151765/3a238ca5-9637-4594-a007-e660406f3eff">

**Comment by tabacitu** [comment]
Nope. Sorry @niladam but adding Uploaders to v5 is not something we can be spending our time on. v5 is the past. v6 is the present. v7 is the future. We are no longer working on anything v5 unless it is a major security problem. [See our policy here](https://github.com/Laravel-Backpack/CRUD/blob/main/SECURITY.md).

Instead of us making a step backwards... I recommend you find a way to make your project make a step forward 😀 Sorry to be so blunt, but we absolutely have to say no to some stuff, in order to say yes to other stuff. Anything v5 is a NO at this point.

Cheers!
